#!/bin/bash
gfortran -fbounds-check ../Modules/Ouyed_random_number_module.f90 ../Modules/Random_numbers_module.f90 ../Modules/Useful_stuff_module.f90 Ising.f90 -o Ising
rm random_numbers_module.mod useful_stuff_module.mod ouyed_random_number_module.mod 
./Ising
#gnuplot MCMC.gp
