#!/bin/bash
gfortran ../Modules/Ouyed_random_number_module.f90 ../Modules/Random_numbers_module.f90 ../Modules/Useful_stuff_module.f90 MCMC.f90 -o MCMC
rm random_numbers_module.mod useful_stuff_module.mod ouyed_random_number_module.mod 
./MCMC
gnuplot MCMC.gp
