#!/bin/bash
gfortran ../Modules/Ouyed_random_number_module.f90 ../Modules/Random_numbers_module.f90 ../Modules/Useful_stuff_module.f90 ../Modules/Metropolis_Hastings_module.f90 Metropolis_Hastings.f90 -o Metropolis_Hastings
rm random_numbers_module.mod useful_stuff_module.mod ouyed_random_number_module.mod metropolis_hastings_module.mod 
./Metropolis_Hastings
gnuplot Metropolis_Hastings.gp
