#!/bin/bash
gfortran ../Modules/Root_finding_module.f90 ../Modules/Ouyed_random_number_module.f90 ../Modules/Random_numbers_module.f90 ../Modules/Useful_stuff_module.f90 PDF_and_Monte_Carlo.f90 -o PDF_and_Monte_Carlo 
rm root_finding_module.mod random_numbers_module.mod useful_stuff_module.mod ouyed_random_number_module.mod beta_func.mod
./PDF_and_Monte_Carlo
gnuplot PDF_and_Monte_Carlo.gp
