#!/bin/bash
gfortran -O3 ../Modules/Ouyed_random_number_module.f90 ../Modules/Random_numbers_module.f90 ../Modules/Useful_stuff_module.f90 Random_generators.f90 -o Random_generators 
rm random_numbers_module.mod useful_stuff_module.mod ouyed_random_number_module.mod
./Random_generators
gnuplot Random_generators.gp
