#!/bin/bash
gfortran ../Modules/Ouyed_random_number_module.f90 ../Modules/Random_numbers_module.f90 ../Modules/Useful_stuff_module.f90 Radiative_transfer.f90 -o Radiative_transfer 
rm random_numbers_module.mod useful_stuff_module.mod ouyed_random_number_module.mod
./Radiative_transfer
gnuplot Radiative_transfer.gp
